server:
  port: 8006

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://tax-dev-rds-mysql-api.cootfk27k5or.ap-northeast-2.rds.amazonaws.com:3306/DTAXDB?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: dtaxasv
    password: qwe123!@#
  quartz-ds:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tax-dev-rds-mysql-api.cootfk27k5or.ap-northeast-2.rds.amazonaws.com:3306/DQUARTZ?autoReconnection=true&useSSL=false&allowMultiQueries=true
      username: dtaxasv
      password: qwe123!@#
  finger-ds:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://tax-dev-rds-mysql-api.cootfk27k5or.ap-northeast-2.rds.amazonaws.com:3306/DFINGER?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: dtaxasv
    password: qwe123!@#
  finger-auto-ds:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tax-dev-rds-mysql-api.cootfk27k5or.ap-northeast-2.rds.amazonaws.com:3306/DFINGERAUTO?autoReconnection=true&useSSL=false&allowMultiQueries=true
      username: dtaxasv
      password: qwe123!@#

logging:
  register-shutdown-hook: false
  config: classpath:logback-dev.xml
  level:
    root: INFO
    com.hanwha.tax.batch: DEBUG
    org.apache.http: INFO
    org.mybatis: WARN

tax:
  api:
    domain: https://api-dev.socratax.io
  sftp:
    user: IS000001
    pwd: d1OryUJJr3
    host: 183.111.160.204
    port: 3300
  mydata:
    path:
      zip: /data/file001/tax_batch/down/
      unzip: /data/file001/tax_batch/open/