server:
  port: 8081

spring:
  .config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://tax-database.c1ttexowmmks.ap-northeast-2.rds.amazonaws.com:3306/tax?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: tax_admin
    password: hli6363!
  quartz-ds:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tax-dbms.cjzouundkjlm.ap-northeast-2.rds.amazonaws.com:3306/quartz?autoReconnection=true&useSSL=false&allowMultiQueries=true
      username: root
      password: welcome123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  register-shutdown-hook: false
  config: classpath:logback-dev.xml
  level:
    root: INFO
    com.hanwha.tax.batch: INFO
    org.apache.http: INFO
    org.mybatis: WARN

tax:
  sftp:
    user: IS000001
    pwd: d1OryUJJr3
    host: 183.111.160.204
    port: 3300

#tax:
#  licence: /home/tax/tax_api/licence/P09510000000_IDS_01_PROD_AES_license.dat