server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://tax-database.c1ttexowmmks.ap-northeast-2.rds.amazonaws.com:3306/tax?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: tax_admin
    password: hli6363!
  quartz-ds:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://tax-dbms.cjzouundkjlm.ap-northeast-2.rds.amazonaws.com:3306/quartz?autoReconnection=true&useSSL=false&allowMultiQueries=true
      username: root
      password: welcome123
  finger-ds:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://tax-dbms.cjzouundkjlm.ap-northeast-2.rds.amazonaws.com:3306/finger?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: root
    password: welcome123

logging:
  register-shutdown-hook: false
  config: /home/ec2-user/tax_batch/config/logback-dev.xml
  level:
    root: INFO
    com.hanwha.tax.batch: DEBUG
    org.apache.http: INFO
    org.mybatis: WARN

tax:
  sftp:
    user: IS000001
    pwd: d1OryUJJr3
    host: 183.111.160.204
    port: 3300